carsaleapp/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("register", views.register_request, name="register"),
    path("otp/<str:username>/<str:phone_number>", views.on_time_password, name="otp"),
    path("login", views.login_request, name="login"),
    path("logout", views.logout_request, name="logout"),
    path("forget_password", views.forget_password_request, name="forget-password"),
    path("reset_password/<str:username>", views.reset_password_request, name="reset-password"),

    path("", views.carviews, name=""),
    path("home", views.carviews, name="home"),
    path("index", views.carviews, name="index"),

    path("cars", views.carviews, name="cars"),
    path("caradd", views.caradd, name="caradd"),
    path("car_details/<int:id>", views.car_detailed_views, name="car_details"),
    path("caredit/<int:id>", views.careditviews, name="caredit"),

    path("favorites", views.favorites_list, name="favorites_list"),
    path("favorites/<int:id>/", views.favorites_add, name="favorites_add"),

    path("elanlar", views.carads_list, name="elanlar"),
    path("elanlar/<int:id>", views.carads_remove, name="carads_remove"),

    path("searchcar", views.searchcar, name="searchcar"),
    path("comment/<int:id>", views.carcomment_add, name="carcomment_add"),
    path("contact", views.contact, name="contact"),
    path("editprofile", views.profile, name="editprofile"),

]

carsaleproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("carsaleapp.urls")),
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

carsaleapp/models.py
from django.db import models
from django.contrib.auth.models import User
from carsaleproject.storage_backends import PublicMediaStorage

from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin, BaseUserManager
from django.utils import timezone
from django.utils.translation import gettext_lazy as _


class CustomManager(BaseUserManager):
    def create_user(self, username, phone_number, password, **extra_fields):
        if not username:
            raise ValueError(_('Username daxil etməlisiniz! '))

        user = self.model(username=username, phone_number=phone_number, **extra_fields)
        user.set_password(password)
        user.save()
        return user

    def create_superuser(self, username, first_name, password, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)
        extra_fields.setdefault('is_active', True)

        if extra_fields.get('is_staff') is not True:
            raise ValueError(_('Superistifadəçi üçün is_staff aktiv olmalıdır!'))
        if extra_fields.get('is_superuser') is not True:
            raise ValueError(_('Superistifadəçi üçün is_superuser aktiv olmalıdır!'))

        return self.create_user(username, first_name, password, **extra_fields)


class NewUser(AbstractBaseUser, PermissionsMixin):
    username = models.CharField(_('username'), max_length=50, unique=True)
    first_name = models.CharField(_('Adınız'), max_length=50, blank=True)
    last_name = models.CharField(_('Soyadınız'), max_length=50, blank=True)
    phone_number = models.CharField(_('Telefon nömrəsi'), max_length=12)
    date_joined = models.DateTimeField(_("Qoşulma tarixi"), default=timezone.now)
    is_staff = models.BooleanField(_("İşçi statusu"), default=False)
    is_active = models.BooleanField(_("Hesab aktivlik statusu"), default=True)
    otp = models.CharField(_('Bir dəfəlik parol'), max_length=4)
    otp_attempts = models.PositiveIntegerField(default=3)

    objects = CustomManager()

    USERNAME_FIELD = 'username'
    REQUIRED_FIELDS = ['first_name', 'last_name']

    def __str__(self):
        return self.username


class CaraddInfo(models.Model):
    option = models.CharField(max_length=50, null=True, blank=True)

    def __str__(self):
        return f"{self.option}"


class Caradd(models.Model):
    user = models.ForeignKey(NewUser, on_delete=models.CASCADE, null=True, blank=True)
    usage = models.CharField(max_length=9, blank=True, null=True)
    brand = models.CharField(verbose_name="marka", max_length=20, blank=True, null=True)
    model = models.CharField(verbose_name="model", max_length=23, blank=True, null=True)
    ban = models.CharField(verbose_name="ban növü", max_length=15, blank=True, null=True)
    color = models.CharField(verbose_name="rəng", max_length=15, blank=True, null=True)
    fuel = models.CharField(verbose_name="yanacaq növü", max_length=15, blank=True, null=True)
    transmitter = models.CharField(verbose_name="ötürücü", max_length=15, blank=True, null=True)
    year = models.CharField(verbose_name="buraxılış ili", max_length=4, null=True, blank=True)
    gearbox = models.CharField(verbose_name="ötür", max_length=20, blank=True, null=True)
    mileage = models.IntegerField(verbose_name="getdiyi yol", null=True, blank=True)
    distanceunit = models.CharField(max_length=5, null=True, blank=True)
    price = models.IntegerField(verbose_name="qiymət", null=True, blank=True)
    priceunit = models.CharField(max_length=8, null=True, blank=True)
    volume = models.IntegerField(verbose_name="mator həcmi", null=True, blank=True)
    power = models.IntegerField(verbose_name="at gücü", null=True, blank=True)
    market = models.CharField(verbose_name="bazar", max_length=15, blank=True, null=True)
    condition = models.CharField(verbose_name="vəziyyəti", max_length=25, blank=True, null=True)
    seats = models.CharField(max_length=13, blank=True, null=True)
    credit = models.CharField(max_length=5, null=True, blank=True)
    swap = models.CharField(max_length=5, null=True, blank=True)
    frontimage = models.ImageField(storage=PublicMediaStorage(), upload_to="front/")
    sideimage = models.ImageField(storage=PublicMediaStorage(), upload_to="side/")
    interiorimage = models.ImageField(storage=PublicMediaStorage(), upload_to="interior/")
    iscomment = models.BooleanField(default=True)
    addinfo = models.TextField(null=True)
    onetimeaddimage = models.BooleanField(default=False)
    isactive = models.BooleanField(default=True)
    caraddinfo = models.ManyToManyField(CaraddInfo, related_name="caraddinfo", default=None, blank=True)
    publish_date = models.DateTimeField(verbose_name="Yayınlanma tarixi: ", auto_now_add=True, null=True)
    favorites = models.ManyToManyField(NewUser, related_name="favorites", default=None, blank=True)

    def __str__(self):
        return f"{self.user}"

    class Meta:
        ordering = ['-publish_date', 'id']


class CarMultipleImages(models.Model):
    carid = models.ManyToManyField(Caradd, related_name='carid', default=None, blank=True)
    images = models.FileField(upload_to='caraddimages/')

    def __str__(self):
        return f"{self.carid}"


class Comment(models.Model):
    car = models.ForeignKey(Caradd, on_delete=models.CASCADE, related_name='comments')
    user = models.ForeignKey(NewUser, on_delete=models.CASCADE)
    content = models.TextField()
    publishdate = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ("publishdate",)

    def __str__(self):
        return f"{self.user}"


class Contact(models.Model):
    user = models.ForeignKey(NewUser, on_delete=models.CASCADE)
    title = models.CharField(max_length=100)
    content = models.TextField()
    contactdate = models.DateTimeField(auto_now_add=True)
    ischoosingme = models.BooleanField(default=False)

    def __str__(self):
        return f"{self.user}"

    class Meta:
        ordering = ("-contactdate",)

carsaleapp/views.py
from .forms import NewComment, NewContactUs
from .models import Caradd, CarMultipleImages
from django.shortcuts import render, redirect, get_object_or_404, HttpResponseRedirect
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.contrib import messages
from django.views.decorators.csrf import csrf_exempt
from .custom_functions import *
import random
from django.urls import reverse


@csrf_exempt
def register_request(request):
    message = random.randint(1000, 9999)
    if request.method == 'POST':
        username = (request.POST["username"]).lower()
        pass1 = request.POST["password1"]
        pass2 = request.POST["password2"]
        phone_number = request.POST["phone_number"]

        if pass1 == pass2:
            if NewUser.objects.filter(username=username).exists():
                messages.error(request, "Bu ad artıq istifadə olunub!")
                return HttpResponseRedirect(request.META.get('HTTP_REFERER', reverse('register')))
            else:
                if NewUser.objects.filter(phone_number=phone_number).exists():
                    messages.error(request, "Bu telefon nömrəsi artıq istifadə olunub!")
                    return HttpResponseRedirect(request.META.get('HTTP_REFERER', reverse('register')))
                else:
                    if len(pass1) < 6:
                        messages.error(request, "Parol minimum 6 simvoldan ibarət olmalıdır!")
                        return HttpResponseRedirect(request.META.get('HTTP_REFERER', reverse('register')))
                    else:
                        if len(phone_number) != 12:
                            messages.error(request, "Telefon nömrəsini düzgün daxil edin!")
                            messages.error(request, "Nümunə: 994602924546")
                            return HttpResponseRedirect(request.META.get('HTTP_REFERER', reverse('register')))
                        else:
                            user = NewUser.objects.create_user(username=username, phone_number=phone_number, password=pass1, is_active=False, otp=message)
                            user.save()
                            send_otp(phone_number, message)

                            messages.success(request, "Qeydiyyatınız uğurla tamamlandı!")
                            messages.success(request,
                                             "Hesabı aktivləşdirmək üçün bir dəfəlik parolu daxil edin!")
                            return redirect('otp', username=username, phone_number=phone_number)
        else:
            messages.error(request, "Parollar eyni deyil!")
            return HttpResponseRedirect(request.META.get('HTTP_REFERER', reverse('register')))
    return render(request, "signup/register.html")


def on_time_password(request, username, phone_number):
    if request.method == "POST":
        otp = request.POST["otp"]
        try:
            user = NewUser.objects.get(username=username, phone_number=phone_number, otp=otp)
            user.is_active = True
            user.otp_attempts -= 1
            user.save()
            messages.success(request, "Hesabınız aktivləşdirildi!")
            return redirect('login')
        except NewUser.DoesNotExist:
            messages.error(request, "Bir dəfəlik parolu düzgün daxil edin! ")
            return HttpResponseRedirect(request.META.get('HTTP_REFERER'))

    return render(request, "signup/otp.html")


@csrf_exempt
def login_request(request):
    if request.method == 'POST':
        username = request.POST["username"]
        password = request.POST["password"]

        user = authenticate(request, username=username, password=password)

        if user is not None:
            login(request, user)
            return redirect("home")
        else:
            messages.error(request, "username və ya password səhvdir!")
            return HttpResponseRedirect(request.META.get('HTTP_REFERER', reverse('register')))
    return render(request, 'signup/login.html')


def logout_request(request):
    logout(request)
    return redirect("home")


def forget_password_request(request):
    if request.method == 'POST':
        username = request.POST["username"]
        try:
            user = NewUser.objects.get(username=username)
            message = random.randint(1000, 9999)
            user.otp = message
            user.save()
            send_otp(user.phone_number, message)
            messages.success(request, "Birdəfəlik parol telefonunuza göndərildi!")
            return redirect('reset-password', username=username)

        except NewUser.DoesNotExist:
            messages.error(request, "Bu adda hesab tapılmadı!")
            return HttpResponseRedirect(request.META.get('HTTP_REFERER'))
    return render(request, 'signup/forget-password.html')


def reset_password_request(request, username):
    user = NewUser.objects.get(username=username)
    if request.method == 'POST':
        password1 = request.POST["password1"]
        password2 = request.POST["password2"]
        otp = request.POST["otp"]
        if otp == user.otp and password1 == password2:
            if len(password1) >= 6:
                user.set_password(password1)
                user.save()
                messages.success(request, "Parolunuz uğurla dəyişdirildi")
                return redirect('login')
            else:
                messages.error(request, "Parol minimum 6 simvoldan ibarət olmalıdır!")
                return HttpResponseRedirect(request.META.get('HTTP_REFERER'))
        elif otp != user.otp and password1 == password2:
            messages.error(request, "Bir dəfəlik parolu düzgün daxil edin!")
            return HttpResponseRedirect(request.META.get('HTTP_REFERER'))
        elif otp == user.otp and password1 != password2:
            messages.error(request, "Parollar eyni deyil!")
            return HttpResponseRedirect(request.META.get('HTTP_REFERER'))
        else:
            messages.error(request, "Daxil etdiyiniz məlumatlarda səhvlik var!")
            return HttpResponseRedirect(request.META.get('HTTP_REFERER'))
    return render(request, 'signup/reset-password.html')


@csrf_exempt
def contact(request):

    if request.method == 'POST':
        contact_form = NewContactUs(request.POST)

        if contact_form.is_valid():
            contact_form.save()
            return render(request, "contact.html", {"success": "İstəyiniz uğurla qeydə alındı!"})

    return render(request, "contact.html")


def profile(request):
    user = NewUser.objects.get(id=request.user.id)

    if request.method == 'POST':
        first_name = request.POST['first_name']
        last_name = request.POST['last_name']
        user.first_name = first_name
        user.last_name = last_name
        user.save()
        messages.success(request, "Uğurla dəyişdirildi")
        return render(request, "profile.html", {"user": user})
    return render(request, "profile.html", {"user": user})


@csrf_exempt
@login_required(login_url="login")
def caradd(request):
    if request.method == 'POST':
        usage = request.POST["usage"]
        brand = request.POST["brand"]
        model = request.POST["model"]
        ban = request.POST["ban"]
        color = request.POST["color"]
        fuel = request.POST["fuel"]
        transmitter = request.POST["transmitter"]
        year = request.POST["year"]
        gearbox = request.POST["gearbox"]
        mileage = request.POST["mileage"]
        distanceunit = request.POST["distanceunit"]
        price = request.POST["price"]
        priceunit = request.POST["priceunit"]
        volume = request.POST["volume"]
        power = request.POST["power"]
        market = request.POST["market"]
        condition = request.POST["condition"]
        seats = request.POST["seats"]
        credit = request.POST["credit"]
        swap = request.POST["swap"]
        front = request.FILES.get('front')
        side = request.FILES.get('side')
        interior = request.FILES.get('interior')
        iscomment = request.POST["iscomment"]
        addinfo = request.POST["addinfo"]
        add_list = request.POST.getlist("addlist")
        new_car = Caradd(
            user=request.user,
            usage=usage,
            brand=brand,
            model=model,
            ban=ban,
            color=color,
            fuel=fuel,
            transmitter=transmitter,
            gearbox=gearbox,
            mileage=mileage,
            distanceunit=distanceunit,
            price=price,
            priceunit=priceunit,
            year=year,
            volume=volume,
            power=power,
            market=market,
            condition=condition,
            seats=seats,
            credit=credit,
            swap=swap,
            frontimage=front,
            sideimage=side,
            interiorimage=interior,
            iscomment=iscomment,
            addinfo=addinfo
        )
        new_car.save()
        for i in add_list:
            new_car.caraddinfo.add(i)
        new_car.save()
        return render(request, "cars/caradd.html", {"success": "Elanınız uğurla dərc edildi! "})
    return render(request, "cars/caradd.html")


def car_detailed_views(request, id):
    car = get_object_or_404(Caradd, id=id)
    context = {"car": car}

    # car comments view
    comments = car.comments.all()
    if request.method == 'POST':
        comment_form = NewComment(request.POST)
        if comment_form.is_valid():
            user_comment = comment_form.save(commit=False)
            user_comment.car = car
            user_comment.save()
            return HttpResponseRedirect('/car_details/' + str(car.id), context)
    else:
        comment_form = NewComment()
    return render(request, "cars/car-details.html", {
        'comments': comments,
        'comments_form': comment_form,
        "car": car,

carsaleapp/templates/contact.html
{% extends 'base.html' %}

{% load static %}
{% block title %} Əlaqə {% endblock %}
{% block content %}

    {% include 'partials/_header.html' %}

    <section class="section section-bg" id="call-to-action" style="background-image: url({% static 'assets/images/banner-image-1-1920x500.jpg' %})">
        <div class="container">
            <div class="row">
                <div class="col-lg-10 offset-lg-1">
                    <div class="cta-content">
                        <br>
                        <br>
                        <h2>Əlaqə saxlamaqdan <em>Çəkinmə</em></h2>
                        <p>Texniki problemlərinizi bizlə bölüşün!</p>
                    </div>
                </div>
            </div>
        </div>
    </section>

    <!-- ***** Features Item Start ***** -->
    <section class="section" id="features">
        <div class="container">
            <div class="row text-center">
                <div class="col-lg-6 offset-lg-3">
                    <div class="section-heading">
                        <h2>Əlaqə <em> məlumatları</em></h2>
                        <img src="{% static 'assets/images/line-dec.png' %}" alt="waves">
                        {% if user.is_authenticated %}
                            {%if success%}<h5 style="background-color: rgba(0, 128, 0, 0.4); line-height: 1.5;">Hörmətli&nbsp;{{user.username}}.&nbsp;{{success}}</h5>{%endif%}
                        {% else %}
                            {%if success%}<h5 style="background-color: rgba(0, 128, 0, 0.4); line-height: 1.5;">{{success}}</h5>{%endif%}
                        {% endif %}
                    </div>
                </div>

                <div class="col-md-4">
                    <div class="icon">
                        <i class="fa fa-phone"></i>
                    </div>

                    <h5><a href="#">+994 70 992 4546</a></h5>

                    <br>
                </div>

                <div class="col-md-4">
                    <div class="icon">
                        <i class="fa fa-envelope"></i>
                    </div>

                    <h5><a href="#">cefersadiq@gmail.com</a></h5>

                    <br>
                </div>

                <div class="col-md-4">
                    <div class="icon">
                        <i class="fa fa-map-marker"></i>
                    </div>

                    <h5>Naxçıvan Muxtar Respublikası</h5>

                    <br>
                </div>
            </div>
        </div>
    </section>
    <!-- ***** Features Item End ***** -->
   
    <!-- ***** Contact Us Area Starts ***** -->
    <section class="section" id="contact-us" style="margin-top: 0">
        <div class="container-fluid">
            <div class="row">
                <div class="col-lg-6 col-md-6 col-xs-12">
                    <div id="map">
                      <iframe src="https://maps.google.com/maps?q=Av.+L%C3%BAcio+Costa,+Rio+de+Janeiro+-+RJ,+Brazil&t=&z=13&ie=UTF8&iwloc=&output=embed" width="100%" height="600px" frameborder="0" style="border:0" allowfullscreen></iframe>
                    </div>
                </div>
                <div class="col-lg-6 col-md-6 col-xs-12">
                    <div class="contact-form section-bg" style="background-image: url({% static 'assets/images/contact-1-720x480.jpg' %})">
                        <form id="contact" method="post">
                          {%csrf_token%}
                          <div class="row">
                            <div class="col-md-6 col-sm-12">
                              <fieldset>
                              {% if user.is_authenticated %}
                                  <input name="user" value={{user.id}} type="hidden" required id="id_user">
                              {% else %}
                                  <input name="user" value={{3}} type="hidden" required id="id_user">
                              {% endif %}
                              </fieldset>
                            </div>
                            <div class="col-md-12 col-sm-12">
                              <fieldset>
                                <input name="title" type="text" placeholder="Başlıq" maxlength="100" required id="id_title">
                              </fieldset>
                            </div>
                            <div class="col-lg-12">
                              <fieldset>
                                <textarea name="content" placeholder="Mesaj" cols="40" rows="10" required id="id_content"></textarea>
                              </fieldset>
                            </div>
                            <div class="col-lg-12">
                              <fieldset>
                                <button type="submit" id="form-submit" class="main-button">Göndər</button>
                              </fieldset>
                            </div>
                          </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- ***** Contact Us Area Ends ***** -->
    
{%endblock%}

carsaleapp/templates/profile.html
{% extends 'base.html' %}

{% load static %}
{% block title %}Hesab əməliyyatları{% endblock %}
{%block csscodes%}
    <style>
        
        .form-control:focus {
            box-shadow: none;
            border-color: #BA68C8
        }
        
        .profile-button {
            background: rgb(99, 39, 120);
            box-shadow: none;
            border: none
        }
        
        .profile-button:hover {
            background: #682773
        }
        
        .profile-button:focus {
            background: #682773;
            box-shadow: none
        }
        
        .profile-button:active {
            background: #682773;
            box-shadow: none
        }
        
        .back:hover {
            color: #682773;
            cursor: pointer
        }
        
        .labels {
            font-size: 11px
        }
        
        .add-experience:hover {
            background: #BA68C8;
            color: #fff;
            cursor: pointer;
            border: solid 1px #BA68C8
        }
    </style>
{%endblock%}

{% block content %}

    {% include 'partials/_header.html' %}
    <br><br><br>

    <form style="margin-bottom: 100px;" method="POST">
    {%csrf_token%}
        <div class="container rounded bg-white mt-5 mb-5">
            <div class="row">
                <div class="col-md-3 border-right">
                    <div class="d-flex flex-column align-items-center text-center p-3 py-5">
                        <img class="rounded-circle mt-5" width="150px" src="{% static 'assets/images/icon.png' %}" value="">
                        <span class="font-weight-bold">
                            <input type="text" name="username" value="{{user.username}}" maxlength="150" required id="id_username" class="form-control" readonly>
                        </span>
                    </div>
                </div>
                <div class="col-md-5 border-right">
                    <div class="p-3 py-5">
                        <div class="d-flex justify-content-between align-items-center mb-3">
                            <h4 class="text-right">Hesab tənzimləmələri</h4><br>
                        </div>
                        {% if messages %}
                            {% for message in messages %}
                                <h4 class="alert {{ message.tags }} m-2"> {{message}} </h4>
                            {% endfor %}
                        {% endif %}
                        <div class="row mt-2">
                            <div class="col-md-6">
                                <label class="labels">Adınız</label>
                                <input type="text" name="first_name" value="{{user.first_name}}" maxlength="150" id="id_first_name" class="form-control">
                            </div>
                            <div class="col-md-6">
                                <label class="labels">Soyadınız</label>
                                <input type="text" name="last_name" value="{{user.last_name}}" maxlength="150" id="id_last_name" class="form-control">
                            </div>
                        </div>
                        <div class="row mt-3">
                            <div class="col-md-12">
                                <label class="labels">Əlaqə nömrəsi</label>
                                <input type="text" name="phone_number" value="{{ user.phone_number }}" maxlength="12" id="id_phone_number" class="form-control" readonly>
                            </div>
                        </div>
                        <div class="mt-5 text-center"><button type="submit" class="btn btn-primary profile-button" type="button">Yadda saxla</button></div>
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="col-md-12">
                        <div class="p-3 py-5">
                            <div class="d-flex justify-content-between align-items-center experience"><h4 class="text-right">Hesab əməliyyatları</h4></div><br>
                            <h3>Tezliklə</h3>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </form>

{%endblock%}